#!/usr/bin/env bash

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

while read -r filename; do
  file -F '' "${filename}" | grep 'shell script' | awk '{print $1}'
done
