#!/usr/bin/env bash

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

{ xargs -d '\n' --no-run-if-empty file -F '' | grep 'shell script' | awk '{print $1}'; } || true
