#!/usr/bin/env bash

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

# shellcheck disable=SC2155
readonly REPO_ROOT="$([[ ${CONFIG_GET_ROOT:-0} == 1 ]] && config-repo-root "${BASH_SOURCE[0]}" || echo "${HOME}")"
readonly GIT_TRY_PULL="${REPO_ROOT}/.my_scripts/util/git-try-pull"
# shellcheck source=../lib/base.sh
source "${REPO_ROOT}/.my_scripts/lib/base.sh"

process_repo() {
  local repo="$1"
  timeout 5 "${GIT_TRY_PULL}" "${repo}" || true
  (
    cd -- "${repo}"
    rif git-diff-sum
  )
}

main() {
  for repo in "$@"; do
    process_repo "${repo}"
  done
}

main "$@"
