#!/usr/bin/env bash

# https://unix.stackexchange.com/a/27014/126543
displaytime() {
  local T=$1
  local D=$((T / 60 / 60 / 24))
  local H=$((T / 60 / 60 % 24))
  local M=$((T / 60 % 60))
  local S=$((T % 60))
  ((D > 0)) && printf '%d days ' $D
  ((H > 0)) && printf '%d hours ' $H
  ((M > 0)) && printf '%d minutes ' $M
  ((D > 0 || H > 0 || M > 0)) && printf 'and '
  printf '%d seconds' $S
}

now="$(date '+%s')"
while IFS=' ' read -r timestamp file; do
  since="$(displaytime $((now - timestamp)))"
  printf '%s:\t%s\n' "${file}" "${since}"
done < <(xargs -d '\n' --no-run-if-empty stat -c '%Y %n' | sort -n)
