#!/usr/bin/env python3
# pylint: disable=invalid-name
import sys
import datetime

def main():
    if len(sys.argv) > 1:
        time_format = sys.argv[1]
    else:
        time_format = '%Y-%m-%d %H:%M:%S.%f'
    for line in sys.stdin:
        time_str = datetime.datetime.now().strftime(time_format)
        print(f'{time_str} {line[:-1]}')


if __name__ == '__main__':
    main()
