#!/usr/bin/env python3
import re
import sys
import urllib.parse

# NOTE: as of 2021-11-19 it seems amzn.com links don't work.

asin_regex = re.compile(r'^/([^/]+/dp|gp/product)/([^/]+)(/|$)')


# https://www.polgarusstudio.com/shorten-amazon-links/
def shorten_amazon_url(url: str):
    parts = urllib.parse.urlparse(url)
    assert parts.netloc.startswith('www.amazon.')
    m = asin_regex.match(parts.path)
    assert m
    product_id = m.groups()[1]
    new_parts = urllib.parse.ParseResult(
        scheme=parts.scheme,
        netloc=parts.netloc.replace('www.amazon', 'amzn'),
        path=f'dp/{product_id}',
        params=parts.params,
        query='',
        fragment=parts.fragment,
    )
    return urllib.parse.urlunparse(new_parts)


def main():
    for url in sys.stdin:
        print(shorten_amazon_url(url))


if __name__ == '__main__':
    main()
# pylint: disable=invalid-name
