#!/usr/bin/env sh
#
# Tests terminal capabilities such as truecolor, styled underlines, bold/italic,
# strikethrough, etc.

# https://gist.github.com/XVilka/8346728
_test_truecolor() {
  awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
  }'
}

_test_basic_styles() {
  printf '\033[1mbold\033[0m\n'
  printf '\033[3mitalic\033[0m\n'
  printf '\033[4munderline\033[0m\n'
  printf '\033[9mstrikethrough\033[0m\n'
  printf '\033[31mred\033[39m\n'
  printf '\033[91mbright red\033[39m\n'
  printf '\033[33myellow\033[39m\n'
  printf '\033[46mcyan background\033[49m\n'
  printf '\033[7mreverse\033[27m\n'
}

# https://askubuntu.com/a/985386/368043
_test_extended_styles() {
  printf '\033[2mdim\033[22m\n'
  printf '\033[21mdouble underline\033[24m\n'
  printf '\033[4:3mcurly underline\033[4:0m\n'
  printf '\033[5mblink\033[25m\n'
  printf '\033[8minvisible\033[28m <- invisible (but copy-pasteable)\n'
  printf '\033[53moverline\033[55m\n'

  printf '\033[38:5:42m256-color, de jure standard (ITU-T T.416)\033[39m\n'
  printf '\033[38;5;42m256-color, de facto standard (commonly used)\033[39m\n'
  printf '\033[38:2::240:143:104mtruecolor, de jure standard (ITU-T T.416)\033[39m\n'
  printf '\033[38;2;240;143;104mtruecolor, de facto standard (commonly used)\033[39m\n'

  printf '\033[48:5:42m256-color background, de jure standard (ITU-T T.416)\033[49m\n'
  printf '\033[48;5;42m256-color background, de facto standard (commonly used)\033[49m\n'
  printf '\033[48:2::240:143:104mtruecolor background, de jure standard (ITU-T T.416)\033[49m\n'
  printf '\033[48;2;240;143;104mtruecolor background, de facto standard (commonly used)\033[49m\n'

  printf '\033[21m\033[58;5;42m256-color double underline\033[59m\033[24m\n'
  printf '\033[4:2m\033[58:2::240:143:104mtruecolor double underline\033[59m\033[4:0m\n'
}

main() {
  sep='---------------------------'
  printf '%s\n' "${sep}"
  echo 'Testing basic styles'
  printf '%s\n' "${sep}"
  _test_basic_styles
  printf '\n%s\n' "${sep}"
  echo 'Testing extended styles'
  printf '%s\n' "${sep}"
  _test_extended_styles
  printf '\n%s\n' "${sep}"
  echo 'Testing truecolor'
  printf '%s\n' "${sep}"
  _test_truecolor
}

main "$@"
