#!/usr/bin/env bash
# tovim
#   got a hint from vim-jp.org
#   http://vim-jp.org/blog/2015/10/15/tovim-on-shell-command-pipes.html
#
# Usage: ls -l | tovim | cut -d: -f1

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

main() {
  local tmpfile
  tmpfile="$(mktemp -t 'tovim.XXXXX')"
  # NOTE: The path variable in trap must be expanded here because it may not be
  # defined when the trap is ran.
  # shellcheck disable=SC2064
  trap "rm -- '${tmpfile}' &> /dev/null || true" EXIT ERR INT HUP TERM
  if [[ -p /dev/stdin ]]; then
    cat - >| "${tmpfile}"
  fi
  vim -- "${tmpfile}" < /dev/tty > /dev/tty
  cat -- "${tmpfile}"
  rm -- "${tmpfile}"
}

main "$@"
