#!/usr/bin/env bash

# This script is copied from https://wiki.archlinux.org/index.php/Xrandr
# TODO: Detect when no monitor is connected. Also, handle non-HDMI1 outpts.

IN="LVDS1"
EXT="HDMI1"

if (xrandr | grep "${EXT} disconnected"); then
  xrandr --output ${EXT} --off --output ${IN} --auto
else
  xrandr --output ${IN} --off --output ${EXT} --auto
fi
