#!/usr/bin/env bash
#
# This is inspired/copied from https://github.com/cknadler/vim-anywhere

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

tmpfile_dir=/tmp/vim-anywhere
tmpfile="${tmpfile_dir}/doc-$(date +"%y%m%d%H%M%S")"

[[ -d ${tmpfile_dir} ]] || mkdir -p -- ${tmpfile_dir}
touch -- "${tmpfile}"

chmod o-rwx -- "${tmpfile}" # Make file only readable by you

if sensible-terminal --window-name 'vim-anywhere' -- vim "${tmpfile}"; then
  xclip -selection clipboard < "${tmpfile}"
fi
