#!/usr/bin/env bash

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

readonly REPO_ROOT="$([[ ${CONFIG_GET_ROOT:-0} == 1 ]] && config-repo-root "${BASH_SOURCE[0]}" || echo "${HOME}")"
# shellcheck source=../lib/base.sh
source "${REPO_ROOT}/.my_scripts/lib/base.sh"

session="$("${REPO_ROOT}/.my_scripts/tmux/tmux-select-session")"
status=$?
# NOTE: fzf returns 130 if the selection was canceled.
if [[ ${status} -ne 0 ]]; then
  exit "${status}"
fi
if [[ -n "${TMUX-}" ]]; then
  tmux switch-client -t "${session}"
else
  tmux attach-session -t "${session}"
fi
