#!/usr/bin/env bash

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

_SELECTOR=(fzf-tmux --multi --select-1 --exit-0)

main() {
  # Fetch visible pane contents and extract URLs.
  mapfile -t urls < <(tmux capture-pane -J -p "$@" | extract-urls)
  if ((${#urls[@]} == 0)); then
    exit 0
  fi
  mapfile -t selected < <(printf '%s\n' "${urls[@]}" | "${_SELECTOR[@]}")
  for url in "${selected[@]}"; do
    sensible-browser "${url}"
  done
}

main "$@"
