#!/usr/bin/env bash

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

readonly HIST_DIR="${HOME}/.local/var/hist/${HOSTNAME}"

# shellcheck disable=SC2034
delim=':::'
# A command to list clients that is usable when presenting to the user.

# TODO: Use the client activity time to infer the current client and
# label it.

# shellcheck disable=SC2034
presentation_header="Session | Size | Last active | Created"
# shellcheck disable=SC2016,SC1004
clients_presentation_cmd='tmux list-clients \
  -F "#{client_session}${delim}#{window_width}x#{window_height}${delim}#{client_activity}${delim}#{client_created}" \
  | sed -r "s|.*$(tty)|[CURRENT] \0|" \
  | gawk -F"${delim}" '"'"'{OFS=" | "; $3=strftime("%Y-%m-%d %H:%M", $3); $4=strftime("%Y-%m-%d %H:%M", $4); print $0}'"'"' \
  | (printf "%s\n" "${presentation_header}" && cat) \
  | column -t -s "|"'
# The presentation must be evaluated only once for both selection and parsing,
# otherwise it might change between them.
clients_presentation="$(eval "${clients_presentation_cmd}")"

# A command to list clients that is easily parsable.
clients_parsing_cmd='tmux list-clients -F "#{client_tty}"'

client_lines_selected=$(
  printf '%s\n' "${clients_presentation}" |
    nl |
    fzf --with-nth '2..' --header-lines=1 --prompt="Clients > " --multi \
      --toggle-sort=ctrl-r \
      "--history=${HIST_DIR}/tmux_detach_client_history" \
      --history-size=100000
)
status=$?
if ((status != 0)); then
  exit ${status}
fi

while IFS='' read -r client_index; do
  # Offset for the header row which is present in the presentation command but not
  # in the parsing command.
  client_index=$((client_index - 1))
  client_tty=$(eval "${clients_parsing_cmd}" | head -n"${client_index}" | tail -n1)
  tmux detach-client -t "${client_tty}"
done < <(awk '{print $1}' <<< "${client_lines_selected}")
