#!/usr/bin/env bash

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

NOCOW_ROOT=(
  '/var/cache'
  '/var/lib/docker'
  '/.snapshots'
  '/swap'
)

NOCOW_HOME=(
  '.cache'
  '.local/pkg'
  '.local/share/selfspy'
  '.local/share/activitywatch'
  '.local/share/pip/log'
  '.local/share/Trash'
  'tmp'
  '.tor-browser'
  '.vscode'
  '.vscode-oss'
  'gdrive'
  '.local/var/libvirt'
  '.config/chromium/Home/Service Worker'
)

_print_warning() {
  local warning normal
  # Yellow color
  warning="$(tput setaf 3 2> /dev/null)" || true
  normal="$(tput sgr0 2> /dev/null)" || true
  printf >&2 '%s\n' "${warning}${*}${normal}"
}

_print_error() {
  local error normal
  # Red color
  error="$(tput setaf 1 2> /dev/null)" || true
  normal="$(tput sgr0 2> /dev/null)" || true
  printf >&2 '%s\n' "${error}${*}${normal}"
}

_print_usage_and_die() {
  _print_error "Usage: $0 --root-dir <ROOT_DIR> --user-dir <USER_DIR>"
  exit 1
}

main() {
  while (($# > 0)); do
    case "$1" in
      --root-dir)
        root="$2"
        shift 2
        ;;
      --user-dir)
        user_dir="$2"
        shift 2
        ;;
      *)
        _print_usage_and_die
        ;;
    esac
  done
  if [[ -z ${root:-} || -z "${user_dir:-}" ]]; then
    _print_usage_and_die
  fi
  for dir in "${NOCOW_ROOT[@]}"; do
    local p="${root}/${dir}"
    if [[ ! -e "${p}" ]]; then
      _print_warning "Path ${p} does not exist"
      continue
    fi
    sudo chattr +C -- "${p}"
  done
  for dir in "${NOCOW_HOME[@]}"; do
    local p="${user_dir}/${dir}"
    if [[ ! -e "${p}" ]]; then
      _print_warning "Path ${p} does not exist"
      continue
    fi
    sudo chattr +C -- "${p}"
  done
}

main "$@"
