#!/usr/bin/env bash

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

readonly REPO_ROOT="$([[ ${CONFIG_GET_ROOT:-0} == 1 ]] && config-repo-root "${BASH_SOURCE[0]}" || echo "${HOME}")"
readonly BASELINE="${REPO_ROOT}/.config/detect-secrets/baseline.json"

main() {
  local tmpfile
  tmpfile="$(mktemp -t "detect-secrets-baseline.XXXX")"
  detect-secrets scan --update "${BASELINE}"
  # jq doesn't support in-place modifications [1], so we use a temporary file as
  # a workaround.
  # [1] https://github.com/stedolan/jq/issues/105
  jq '.exclude.files = "detect-secrets/baseline\\.json"' "${BASELINE}" >| "${tmpfile}"
  cp -f -- "${tmpfile}" "${BASELINE}"
  detect-secrets audit "${BASELINE}"
}

main "$@"
