#!/usr/bin/env bash

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

# shellcheck disable=SC2155
readonly REPO_ROOT="$([[ ${CONFIG_GET_ROOT:-0} == 1 ]] && config-repo-root "${BASH_SOURCE[0]}" || echo "${HOME}")"

main() {
  local str
  str="$(rofi -dmenu -p 'Keys' -theme-str 'window {width: 60ch;} listview {lines: 0;}')"
  if [[ -z "${str}" ]]; then
    exit 1
  fi
  "${REPO_ROOT}/.my_scripts/keyboard/string_to_xdotool_key_args.py" "${str}" |
    xargs xdotool key
}

main "$@"
