#!/usr/bin/env bash

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

main() {
  if (($# < 2)); then
    printf >&2 '%s requires at least two arguments\n' "$0"
    exit 1
  fi
  if ! /opt/ikl/is-x11-ready; then
    log 'Graphical system not ready yet, exiting'
    exit
  fi
  local logging_name="$1"
  local script_path="$2"
  shift 2
  "${script_path}" "$@" |& logger -t "${logging_name}"
}

main "$@"
