#!/usr/bin/env bash

# TODO: Use lockfiles for more reprodocible environments. See:
# - https://github.com/conda-incubator/conda-lock
# - https://github.com/jazzband/pip-tools

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

# shellcheck disable=SC2155
readonly REPO_ROOT="$([[ ${CONFIG_GET_ROOT:-0} == 1 ]] && config-repo-root "${BASH_SOURCE[0]}" || echo "${HOME}")"
readonly SUBMODULES_DIR="${REPO_ROOT}/submodules"
readonly CONDA_LOCAL_DIR="${HOME}/.local/pkg/conda"
readonly CONDA="${CONDA_LOCAL_DIR}/bin/conda"
readonly CONDA_TOOLS_BIN_DIR="${CONDA_LOCAL_DIR}/envs/tools/bin"
readonly MINICONDA_INSTALLER='Miniconda3-py39_4.10.3-Linux-x86_64.sh'
readonly MINICONDA_SHA256='1ea2f885b4dbc3098662845560bc64271eb17085387a70c2ba3f29fff6f8d52f' # pragma: allowlist secret

# shellcheck source=../.my_scripts/lib/platform_detection.sh
source "${REPO_ROOT}/.my_scripts/lib/platform_detection.sh"
# shellcheck source=setup_installation_env
source "${REPO_ROOT}/install/setup_installation_env"

declare -A INSTALLED_BINARIES=(
  ['black']=''
  ['buku']=''
  ['codespell']=''
  ['conda-docker']=''
  ['conda-lock']=''
  ['detect-secrets']=''
  ['detect-secrets-hook']=''
  # gh
  ['git-nbdiffdriver']=''
  ['git-nbdifftool']=''
  ['git-nbmergedriver']=''
  ['git-nbmergetool']=''
  ['gitlab']=''
  # gitsome
  ['glances']=''
  ['gping']=''
  ['gpu']='gpu-cli'
  ['gpustat']=''
  ['grip']=''
  ['ipython']=''
  ['isort']=''
  ['jupyter']=''
  ['jupyter-qtconsole']=''
  ['jupytext']=''
  ['litecli']=''
  ['mamba']=''
  ['mansnip']=''
  ['nbdiff']=''
  ['nbdiff-web']=''
  ['nbdime']=''
  ['nbmerge']=''
  ['nbmerge-web']=''
  ['nbshow']=''
  ['pip']=''
  ['pipenv']=''
  ['pipenv-resolver']=''
  ['poetry']=''
  ['proselint']=''
  ['py']=''
  ['pydf']=''
  ['pylint']=''
  ['semantic-release']='python-semantic-release'
  ['pytype']=''
  ['s-tui']=''
  ['semgrep']=''
  ['twine']=''
  ['ueberzug']=''
  ['undervolt']=''
  ['vint']=''
  ['yapf']=''
)

_print_bold() {
  local bold normal
  bold="$(tput bold 2> /dev/null)" || true
  normal="$(tput sgr0 2> /dev/null)" || true
  printf '%s' "${bold}"
  printf '%s' "${@}"
  printf '%s\n' "${normal}"
}

_log_info() {
  printf 'install-python-packages: %s\n' "$*"
}

_log_info_bold() {
  _print_bold "$(_log_info "$@")"
}

_print_error() {
  local error normal
  # Red color
  error="$(tput setaf 1 2> /dev/null)" || true
  normal="$(tput sgr0 2> /dev/null)" || true
  printf >&2 '%s\n' "${error}${*}${normal}"
}

_log_error() {
  _print_error "$(printf 'install-python-packages: %s' "$*")"
}

_print_usage_and_die() {
  _print_error "$(printf 'Usage: %s [--graphical] [--non-graphical]' \
    "$(basename "$0")")"
  exit 1
}

_fastest_conda() {
  local bin="${CONDA}"
  # As of 2020-10-14, mamba wasn't faster than conda in this script, though I
  # think it's faster when installing envrionments from scratch. I'll consider
  # enabling it in the future.
  # As of 2021-10-16, mamba was faster: 1 minute vs 3.5 minutes. However,
  # it doesn't seem idempotent with conda, so the first time switching between
  # them will take longer.
  # As of 2021-11-05, I ran into the following issues with mamba:
  # - It doesn't register an environment when conda when installing it with
  #   `mamba update` since it sometimes installs it to the tools environment
  #   (which is where mamba is installed).
  # - It doesn't install new conda dependencies in existing environments
  if [[ -x "${CONDA_TOOLS_BIN_DIR}/mamba" ]]; then
    bin="${CONDA_TOOLS_BIN_DIR}/mamba"
  fi
  "${bin}" "$@"
}

_create_python_env_wrappers() {
  # Source profile again to make sure create-wrappers is in the PATH.
  # shellcheck source=../.profile
  source "${REPO_ROOT}/.profile"

  # NOTE: As of 2018-11-25 I'm using the conda-run script instead of generating
  # wrappers.
  _log_info_bold "Installing conda exec-wrappers"
  pip install exec-wrappers
  # cd "${SUBMODULES_DIR}/exec-wrappers"
  # "${HOME}/.local/pkg/conda/bin/python" setup.py install
  _log_info_bold 'Creating python environment wrappers'
  # local envs=(i3_scripts shell_history)
  # local bin_dirs=("${HOME}/.my_scripts/i3" "${HOME}/.config/bash/history")
  local envs=()
  local bin_dirs=()
  for i in "${!envs[@]}"; do
    local dest_dir="${bin_dirs[${i}]}/wrappers"
    [[ -d ${dest_dir} ]] || mkdir -- "${dest_dir}"
    "${CONDA_TOOLS_BIN_DIR}/create-wrappers" --type conda \
      --conda-env-dir "${CONDA_LOCAL_DIR}/envs/${envs[${i}]}" \
      --bin-dir "${bin_dirs[${i}]}" \
      --dest-dir "${dest_dir}"
  done
}

_install_conda() {
  # TODO: Install man pages. I need to clone:
  # https://github.com/conda/conda-docs
  # And then build the man files and link them to my path.
  if [[ -d ${CONDA_LOCAL_DIR} ]]; then
    _log_info_bold 'Looks like miniconda is already installed'
    return
  fi
  _log_info_bold 'Installing miniconda'
  cd -- "${INSTALLATION_TMP_DIR}"
  wget --continue "https://repo.continuum.io/miniconda/${MINICONDA_INSTALLER}"
  if ! sha256sum --status --check - <<< "${MINICONDA_SHA256} ${MINICONDA_INSTALLER}"; then
    _log_error 'Miniconda installer sha256 check failed'
    return 1
  fi
  bash "${MINICONDA_INSTALLER}" -b -p "${CONDA_LOCAL_DIR}"
}

_install_conda_env() {
  local file="${1:-environment.yml}"
  # Some conda environment files install pip dependencies from a
  # requirements.txt file. It seems that in this case we must resolve symlinks
  # for this to work so that the requirements.txt file can be found by conda.
  file="$(readlink -f -- "${file}")"
  local dir
  dir="$(dirname -- "${file}")"
  # Workaround for mamba sometimes installing stuff with the wrong prefix
  local env_name
  env_name="$(grep -E '^\s*name: [a-zA-Z_][a-zA-Z0-9_-]*' -- "${file}" |
    sed -E 's/^\s*name:\s*//')"
  local env_prefix="${CONDA_LOCAL_DIR}/envs/${env_name}"
  if [[ -e "${env_prefix}" ]]; then
    _log_info_bold "Updating conda environment ${env_name} from ${file}"
    # --prune should remove packages not specified in environment file, though
    # it's broken as of 2020-11-02: https://github.com/conda/conda/issues/7279
    local cmd=(_fastest_conda env update --prune -p "${env_prefix}" -f "${file}")
  else
    _log_info_bold "Installing conda environment ${env_name} from ${file}"
    local cmd=(_fastest_conda env create -p "${env_prefix}" -f "${file}")
  fi
  (
    cd -- "${dir}"
    if ! "${cmd[@]}"; then
      _log_info_bold 'Removing compiler_compat/ld and retrying'
      rm -- "${CONDA_LOCAL_DIR}/compiler_compat/ld" \
        "${CONDA_LOCAL_DIR}"/envs/*/compiler_compat/ld &> /dev/null || true
      "${cmd[@]}"
    fi
  )
}

_install_conda_envs_from_dir() {
  local dir="$1"
  while IFS= read -r -d '' file; do
    _install_conda_env "${file}"
  done < <(\find -L "${dir}" -maxdepth 1 -type f -print0 | sort --zero-terminated)
}

_install_non_graphical_conda_envs() {
  _log_info_bold 'Installing non-graphical conda environments'
  _install_conda_env "${REPO_ROOT}/.config/bash/history/environment.yml"
  _install_conda_env "${REPO_ROOT}/install/conda_envs/urlextract/urlextract.yml"
  _install_conda_env "${REPO_ROOT}/install/conda_envs/tools.yml"
  _symlink_tools_binaries
}

_install_graphical_conda_envs() {
  _log_info_bold 'Installing graphical conda environments'
  _install_conda_env "${SUBMODULES_DIR}/keydope/environment.yml"
  _install_conda_env "${SUBMODULES_DIR}/desktop/i3-workspace-groups/environment.yml"
  _install_conda_env "${SUBMODULES_DIR}/desktop/i3-scratchpad/environment.yml"
  _install_conda_env "${REPO_ROOT}/.my_scripts/i3/environment.yml"
  _install_conda_env "${REPO_ROOT}/install/conda_envs/i3_resurrect/i3_resurrect.yml"
  _install_conda_env "${SUBMODULES_DIR}/desktop/selfspy/environment.yml"
  _install_conda_env "${REPO_ROOT}/.my_scripts/desktop_env/suspend-screenlock/environment.yml"
}

_setup_conda() {
  # shellcheck disable=SC2119
  do_basic_setup
  _install_conda
  # Source profile again to get the conda bin path.
  # shellcheck source=../.profile
  source "${REPO_ROOT}/.profile"
  _log_info_bold 'Updating conda'
  # NOTE: we must specify the environment in case another environment is active
  # when this script is called.
  # NOTE: if conda-build is not installed, updating conda will fail.
  "${CONDA}" install --name base --channel defaults --yes conda-build
  "${CONDA}" update --name base --channel defaults --yes conda
  _log_info_bold 'Removing compiler_compat/ld'
  rm "${CONDA_LOCAL_DIR}/compiler_compat/ld" \
    "${CONDA_LOCAL_DIR}"/envs/*/compiler_compat/ld &> /dev/null || true
}

_symlink_tools_binaries() {
  _log_info_bold 'Symlinking binaries from conda tools environment'
  local bin install_name
  for bin in "${!INSTALLED_BINARIES[@]}"; do
    if [[ -n "${INSTALLED_BINARIES[${bin}]}" ]]; then
      install_name="${INSTALLED_BINARIES[${bin}]}"
      _log_info "Installing ${bin} as ${install_name}"
    else
      install_name="${bin}"
      _log_info "Installing ${bin}"
    fi
    symlink_binary "${CONDA_TOOLS_BIN_DIR}/${bin}" "${install_name}"
  done
}

main() {
  local install_non_graphical=0
  local install_graphical=0
  if (($# == 0)); then
    install_non_graphical=1
    install_graphical=1
  fi
  while (($# > 0)); do
    case "$1" in
      --non-graphical)
        install_non_graphical=1
        shift 1
        ;;
      --graphical)
        install_graphical=1
        shift 1
        ;;
      *)
        _print_usage_and_die
        ;;
    esac
  done

  _setup_conda
  for base_tool in conda activate deactivate; do
    symlink_binary "${CONDA_LOCAL_DIR}/bin/${base_tool}" "${base_tool}"
  done
  if ((install_non_graphical)); then
    _install_non_graphical_conda_envs
  fi
  if ((install_graphical)); then
    _install_graphical_conda_envs
  fi
}

main "$@"
