#!/usr/bin/env python3
import argparse
import json
import os
import stat
import subprocess

import installation_util as util

# The node modules will be installed in a directory named node_modules under
# this directory.
# NOTE: `yarn global add` installs packages to ~/.config/yarn/global by default.
LOCAL_MODULES_PARENT_DIR = os.path.expanduser('~/.local/pkg/npm')
XDG_DATA_HOME = os.environ.get('XDG_DATA_HOME',
                               os.path.expandvars('$HOME/.local/share'))


def _install_packages():
    subprocess.run(['yarn', 'install'],
                   cwd=LOCAL_MODULES_PARENT_DIR,
                   check=True)


def _get_npm_config_var(name: str):
    p = subprocess.run(['npm', 'config', 'get', name],
                       check=True,
                       stdout=subprocess.PIPE,
                       universal_newlines=True)
    return p.stdout.strip()


# https://yarnpkg.com/cli/set/version
def _upgrade_yarn():
    subprocess.run(['yarn', 'set', 'version', 'berry'],
                   cwd=LOCAL_MODULES_PARENT_DIR,
                   check=True)


def _upgrade_packages(packages):
    # NOTE(infokiller): This doesn't upgrade package.json with the new versions,
    # see: https://github.com/yarnpkg/yarn/issues/3266
    # Steps:
    # 1. Upgrade using `--latest` to get the latest versions of all packages,
    #    which may upgrade the major version, thus breaking stuff (but I'm
    #    living on the bleeding edge...). Since the `package.json` file is in
    #    the config repo, I should notice any changes before committing them.
    # 2. Upgrade using `--carret` to register the major versions for each
    #    package in `package.json`, so that all my computers use consistent
    #    package versions.
    # subprocess.run(['yarn', 'upgrade', '--latest'],
    #                cwd=LOCAL_MODULES_PARENT_DIR,
    #                check=True)
    # subprocess.run(['yarn', 'upgrade', '--caret'],
    #                cwd=LOCAL_MODULES_PARENT_DIR,
    #                check=True)
    subprocess.run(['yarn', 'add'] + packages + ['--exact'],
                   cwd=LOCAL_MODULES_PARENT_DIR,
                   check=True)


# https://docs.npmjs.com/cli/v8/configuring-npm/package-json#man
def _get_man_files(package_path, package_metadata):
    man_files = package_metadata.get('man', [])
    if isinstance(man_files, str):
        man_files = [man_files]
    man_files = [os.path.join(package_path, p) for p in man_files]
    man_dir = package_metadata.get('directories', {}).get('man')
    if man_dir:
        man_dir = os.path.join(package_path, man_dir)
    # Not sure what to do in this case, so log a warning for now.
    if man_files and man_dir:
        util.log_warning('"man" and "directories.man" are both specified')
    if man_files:
        return man_files
    # NOTE: I'm not sure if the man directory must have all man files directly
    # under it or can have it under subdirectories, but it seems like the former
    # based on actual usage:
    # https://github.com/search?q=filename%3A%22package.json%22+language%3Ajson+directories+man&type=Code
    if man_dir:
        return [os.path.join(man_dir, p) for p in os.listdir(man_dir)]
    return []


def _link_package_files(package_path, get_binary_install_name=lambda x: x):
    package_spec = os.path.basename(package_path)
    package_metadata_path = os.path.join(package_path, 'package.json')
    with open(package_metadata_path, encoding='utf8') as f:
        package_metadata = json.loads(f.read())
    package_bins = package_metadata.get('bin', {})
    if isinstance(package_bins, str):
        package_bins = {package_spec: package_bins}
    assert isinstance(package_bins, dict)
    for name, path in package_bins.items():
        install_name = get_binary_install_name(name)
        if install_name is None:
            util.log_warning(f'Skipping binary not explicitly listed: {name}')
            continue
        if not install_name:
            util.log_info(f'Skipping explicitly disabled binary: {name}')
            continue
        util.log_info(f'Installing binary {name} from package {package_spec} '
                      f'as {install_name}')
        # I ran into a case where the file is not executable, for example
        # build/src/index.js in clasp 2.4.2.
        bin_src_path = os.path.join(package_path, path)
        os.chmod(bin_src_path, os.stat(bin_src_path).st_mode | stat.S_IEXEC)
        util.symlink_relative(bin_src_path,
                              os.path.join(util.USER_BIN_DIR, install_name))
    man_files = _get_man_files(package_path, package_metadata)
    # The package.json docs say: "If only a single file is provided, then it's
    # installed such that it is the result from man <pkgname>, regardless of its
    # actual filename".
    if len(man_files) == 1:
        parts = man_files[0].split('.')
        ext_parts = parts[-2:] if parts[-1] == 'gz' else parts[-1:]
        install_name = '.'.join([package_spec] + ext_parts)
        util.install_man_file(man_files[0], install_name)
        return
    for path in _get_man_files(package_path, package_metadata):
        # The package.json docs say: "If the filename doesn't start with the
        # package name, then it's prefixed.".
        name = os.path.basename(path)
        if not name.startswith(package_spec):
            name = f'{package_spec}-{name}'
        util.install_man_file(path, name)


# Install pnpm without assuming node is installed. Not really used for now.
# https://pnpm.io/installation
def _install_pnpm_via_script():
    zshrc_path = os.path.expanduser('~/.zshrc')
    # THe pnpm install script modifies .zshrc (and ignores ZDOTDIR).
    zshrc_exists_before = os.path.isfile(zshrc_path)
    subprocess.run('curl -fsSL https://get.pnpm.io/install.sh | sponge | sh',
                   check=True,
                   shell=True)
    zshrc_exists_after = os.path.isfile(zshrc_path)
    if zshrc_exists_after and not zshrc_exists_before:
        os.remove(zshrc_path)
    pnpm_path = os.path.join(XDG_DATA_HOME, 'pnpm/pnpm')
    # print(pnpm_path)
    assert os.path.isfile(pnpm_path)
    util.symlink_relative(pnpm_path, os.path.join(util.USER_BIN_DIR, 'pnpm'))


# https://pnpm.io/installation
def _install_pnpm_via_npm():
    subprocess.run('npm install -g pnpm', check=True, shell=True)
    npm_prefix = _get_npm_config_var('prefix')
    for file in ['pnpm', 'pnpx']:
        path = os.path.join(npm_prefix, 'bin', file)
        util.symlink_relative(path, os.path.join(util.USER_BIN_DIR, file))


def main():
    parser = argparse.ArgumentParser(
        description='Install and/or upgrade config repo npm packages.')
    parser.add_argument('--upgrade',
                        action='store_true',
                        help='Upgrade npm packages to their latest version.')
    args = parser.parse_args()

    util.log_name = 'install-npm-packages'
    util.create_user_dirs()

    _install_pnpm_via_npm()
    if args.upgrade:
        _upgrade_yarn()
    _install_packages()
    with open(os.path.join(LOCAL_MODULES_PARENT_DIR, 'package.json')) as f:
        packages_json = json.loads(f.read())
    packages = list(packages_json.get('dependencies', {}).keys())
    if args.upgrade:
        _upgrade_packages(packages)

    explicitly_installed_binaries = packages_json.get(
        'explicitly_installed_binaries', {})
    for package in packages:
        get_binary_install_name = lambda x: x
        if package in explicitly_installed_binaries:
            get_binary_install_name = explicitly_installed_binaries[package].get
        package_path = os.path.join(LOCAL_MODULES_PARENT_DIR, 'node_modules',
                                    package)
        _link_package_files(package_path, get_binary_install_name)


if __name__ == "__main__":
    main()
