# For a list of available options see https://prettier.io/docs/en/options.html

# Options not set in this file should have defaults that already match Google's
# style from: https://github.com/google/ts-style

# Note that prettier reads indentation size and type (tabs/spaces) from
# editorconfig if it finds an editorconfig file, so these settings should only
# be set on the editorconfig file to preserve consistency. See also:
# https://github.com/prettier/prettier/issues/42#issuecomment-327073326

singleQuote: true
