# shellcheck shell=bash
# System hardening config with no X11/Wayland/GUI or networking dependencies.
# Security packages with networking dependencies should be configured in
# hardening-network.sh.

# Security and backups, no X11 dependencies.
AddPackage linux-hardened # The Linux-hardened kernel and modules
AddPackage cryptsetup     # Userspace setup tool for transparent encryption of block devices using dm-crypt
AddPackage polkit         # Application development toolkit for controlling system-wide privileges
AddPackage arch-audit     # An utility like pkg-audit based on Arch CVE Monitoring Team data

AddPackage apparmor # Linux application security framework - mandatory access control for programs (metapackage)
CreateLink '/etc/systemd/system/multi-user.target.wants/apparmor.service' '/usr/lib/systemd/system/apparmor.service'

AddPackage rng-tools # Random number generator related utilities
CreateLink '/etc/systemd/system/sysinit.target.wants/rngd.service' '/usr/lib/systemd/system/rngd.service'

AddPackage clamav # Anti-virus toolkit for Unix
CreateLink '/etc/systemd/system/multi-user.target.wants/clamav-daemon.service' '/usr/lib/systemd/system/clamav-daemon.service'
CreateLink '/etc/systemd/system/sockets.target.wants/clamav-daemon.socket' '/usr/lib/systemd/system/clamav-daemon.socket'
CreateLink '/etc/systemd/system/multi-user.target.wants/clamav-freshclam.service' '/usr/lib/systemd/system/clamav-freshclam.service'

CopyFile '/etc/audit/rules.d/chrome.rules'
# Autogenerated audit file.
IgnorePath '/etc/audit/audit.rules'
CopyFile '/etc/modprobe.d/blacklist.conf'
# TODO: Check if I can put my pam changes in separate files to avoid getting
# conflicts when the distro files are updated.
AddPackage pam-u2f                     # Universal 2nd Factor (U2F) PAM authentication module from Yubico
AddPackage yubico-pam                  # Yubico YubiKey PAM module
AddPackage libpam-google-authenticator # PAM module for google authenticator app
CopyFile '/etc/pam.d/sudo'
CopyFile '/etc/pam.d/su'
CopyFile '/etc/pam.d/su-l'
cat >> "$(GetPackageOriginalFile pambase /etc/pam.d/system-login)" << 'EOF'
# NOTE(infokiller): this adds a delay of 5 seconds to auth failures.
auth       optional   pam_faildelay.so     delay=5000000
EOF
# NOTE: Customizing /etc/pam.d/sshd is disabled, since it current doesn't change
# anything. Previously, it was used to add Google Authenticator support to sshd.
# CopyFile '/etc/pam.d/sshd'
# NOTE: Customizing /etc/pam.d/passwd is disabled. It was used to increase the number of
# hashing rounds for new SHA512-hashed passwords [1][2], but as of 2023-09-25 Archlinux  is
# using yescrypt for new passwords [3].
# [1] https://wiki.archlinux.org/title/SHA_password_hashes
# [2] password	required	pam_unix.so sha512 shadow nullok rounds=100000
# [3] https://archlinux.org/news/changes-to-default-password-hashing-algorithm-and-umask-settings/ 
# CopyFile '/etc/pam.d/passwd'
CopyFile '/etc/sysctl.d/99-hardening.conf' 600

cat >> "$(GetPackageOriginalFile shadow '/etc/login.defs')" << 'EOF'
# See documentation
UMASK	077

# NOTE(infokiller): Setting these variables was suggested by Lynis.
SHA_CRYPT_MIN_ROUNDS 100000
SHA_CRYPT_MAX_ROUNDS 1000000
EOF

# Relax login denial after failed attempts. The default is to deny login for 10
# minutes of 3 failed attempts, we change it to 30 seconds after 5 failed
# attempts.
cat >> "$(GetPackageOriginalFile pam '/etc/security/faillock.conf')" << 'EOF'

#########################################################################
# Changes by infokiller
#########################################################################

deny = 5
fail_interval = 60
unlock_time = 30
EOF

# We don't want to enable usbguard automatically because it can make the OS
# unusable by blocking the keyboard. In this situation, the user is expected to
# manually whitelist the right devices before enabling usbguard.
if function_exists 'is_usbguard_enabled' && is_usbguard_enabled; then
  AddPackage usbguard # Software framework for implementing USB device authorization policies
  CopyFile '/etc/usbguard/rules.conf'
  CopyFile '/etc/usbguard/usbguard-daemon.conf'
  CopyFile '/etc/systemd/system/usbguard.service.d/override.conf'
  CreateLink '/etc/systemd/system/dbus-org.usbguard.service' '/usr/lib/systemd/system/usbguard-dbus.service'
  CreateLink '/etc/systemd/system/multi-user.target.wants/usbguard-dbus.service' '/usr/lib/systemd/system/usbguard-dbus.service'
fi

# NOTE: ${ACONF_LIB} is defined in 00-helpers.sh.
# As of 2023-02-14, firejail is disabled because of too many issues with
# bugs in program profiles the need to customize them to fix it.
# source "${ACONF_LIB}/firejail.sh"
