global !p
from ultisnips_util import get_ale_lint_codes
endglobal

snippet "hadolint-disable|dl" "Disable hadolint errors in next line" rb
# hadolint ignore=${1:`!p snip.rv = ','.join(get_ale_lint_codes('hadolint'))`}
endsnippet
