#!/usr/bin/env bash

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o errexit -o errtrace -o nounset -o pipefail

_print_error() {
  local error normal
  # Red color
  error="$(tput setaf 1 2> /dev/null)" || true
  normal="$(tput sgr0 2> /dev/null)" || true
  printf >&2 '%s\n' "${error}${*}${normal}"
}

main() {
  # Prevent pushes to branches with "prx" or "prv" in their name
  # https://stackoverflow.com/a/30471886
  if grep -E --color=auto 'prx|prv'; then
    _print_error 'pre-push: preventing push to private looking branch'
    return 1
  fi
}

main "$@"
