#!/usr/bin/env python3

import i3ipc

BORDERS = [
    ('pixel', 1),
    ('pixel', 3),
    ('normal', 3),
    ('none', 0),
]


def main():
    i3_connection = i3ipc.Connection()
    tree = i3_connection.get_tree()
    focused_container = tree.find_focused()
    try:
        index = BORDERS.index((focused_container.border,
                               focused_container.current_border_width))
        next_index = (index + 1) % len(BORDERS)
    except ValueError:
        next_index = 0
    next_border = BORDERS[next_index]
    if next_border[0] == 'none':
        cmd = 'border none'
    else:
        cmd = 'border {} {}'.format(next_border[0], next_border[1])
    focused_container.command(cmd)


if __name__ == '__main__':
    main()
