-- https://github.com/nvim-treesitter/nvim-treesitter#modules
vim.defer_fn(function()
  require('nvim-treesitter.configs').setup {
    ensure_installed = {
      'bash',
      'c',
      'cmake',
      'comment',
      'cpp',
      'css',
      'dockerfile',
      'dot',
      -- 'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'go',
      'gomod',
      -- 'gosum',
      'help',
      -- 'hjson',
      'html',
      'http',
      -- 'ini',
      'javascript',
      -- 'jsdoc',
      'json',
      -- 'json5',
      'jsonc',
      -- 'jq',
      'latex',
      'lua',
      'make',
      'markdown',
      -- As of 2023-07-26, markdown_inline causes an error "query: invalid node
      -- type" on some files.
      -- 'markdown_inline',
      -- 'nix',
      'python',
      -- 'r',
      'rasi',
      'regex',
      'rst',
      'rust',
      'toml',
      -- 'tsx',
      'typescript',
      'vim',
      'yaml',
    },
    highlight = {
      enable = true,
    },
    -- indent = {
    --   enable = true,
    -- },
  }
end, 0)
