name: Vint
on: [push, pull_request]
jobs:
  vint:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup dependencies
      run: pip install vim-vint
    - name: Run Vint in vim mode
      run: vint .
    - name: Run Vint in neovim mode
      run: vint --enable-neovim .
